[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "filamux-ui"
version = "0.1.0"
dependencies = [
    "pyside6==6.7.0",
    "protobuf==5.27.0",
    "crc==7.0.0"
]

