# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x07\x66ilamux*\x87\x01\n\x0bMessageType\x12\x18\n\x14MSG_GET_SPOOL_PARAMS\x10\x01\x12\x18\n\x14MSG_SET_SPOOL_PARAMS\x10\x02\x12\x18\n\x14MSG_SET_TARGET_SPOOL\x10\x03\x12\x12\n\x0eMSG_GET_STATUS\x10\x04\x12\x16\n\x12MSG_EXTRUDER_GCODE\x10\n')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=26
  _MESSAGETYPE._serialized_end=161
# @@protoc_insertion_point(module_scope)
