# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extruder_gcode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65xtruder_gcode.proto\x12\x07\x66ilamux\"!\n\x10\x45xtruderGCodeReq\x12\r\n\x05gcode\x18\x01 \x02(\t\"a\n\x10\x45xtruderGCodeRes\x12\x30\n\x06status\x18\x01 \x02(\x0e\x32 .filamux.ExtruderGCodeRes.Status\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\n')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extruder_gcode_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXTRUDERGCODEREQ._serialized_start=33
  _EXTRUDERGCODEREQ._serialized_end=66
  _EXTRUDERGCODERES._serialized_start=68
  _EXTRUDERGCODERES._serialized_end=165
  _EXTRUDERGCODERES_STATUS._serialized_start=138
  _EXTRUDERGCODERES_STATUS._serialized_end=165
# @@protoc_insertion_point(module_scope)
