# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extruder_feed.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65xtruder_feed.proto\x12\x07\x66ilamux\"2\n\x0f\x45xtruderFeedReq\x12\r\n\x05speed\x18\x01 \x02(\r\x12\x10\n\x08\x64istance\x18\x02 \x02(\x05\".\n\x0f\x45xtruderFeedRes\x12\n\n\x02ok\x18\x01 \x02(\x08\x12\x0f\n\x06reason\x18\xff\x01 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extruder_feed_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXTRUDERFEEDREQ._serialized_start=32
  _EXTRUDERFEEDREQ._serialized_end=82
  _EXTRUDERFEEDRES._serialized_start=84
  _EXTRUDERFEEDRES._serialized_end=130
# @@protoc_insertion_point(module_scope)
