# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_spool_params.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16get_spool_params.proto\x12\x07\x66ilamux\"\"\n\x11GetSpoolParamsReq\x12\r\n\x05index\x18\x01 \x02(\x05\"<\n\x11GetSpoolParamsRes\x12\x0e\n\x06\x61\x63tive\x18\x01 \x02(\x08\x12\x17\n\x0flengthRemaining\x18\x02 \x02(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_spool_params_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETSPOOLPARAMSREQ._serialized_start=35
  _GETSPOOLPARAMSREQ._serialized_end=69
  _GETSPOOLPARAMSRES._serialized_start=71
  _GETSPOOLPARAMSRES._serialized_end=131
# @@protoc_insertion_point(module_scope)
