# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_spool_params.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16set_spool_params.proto\x12\x07\x66ilamux\"2\n\x11SetSpoolParamsReq\x12\r\n\x05index\x18\x01 \x02(\x05\x12\x0e\n\x06length\x18\x02 \x02(\x05\"0\n\x11SetSpoolParamsRes\x12\n\n\x02ok\x18\x01 \x02(\x08\x12\x0f\n\x06reason\x18\xff\x01 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'set_spool_params_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETSPOOLPARAMSREQ._serialized_start=35
  _SETSPOOLPARAMSREQ._serialized_end=85
  _SETSPOOLPARAMSRES._serialized_start=87
  _SETSPOOLPARAMSRES._serialized_end=135
# @@protoc_insertion_point(module_scope)
