# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_target_spool.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16set_target_spool.proto\x12\x07\x66ilamux\"\"\n\x11SetTargetSpoolReq\x12\r\n\x05index\x18\x01 \x02(\x05\"0\n\x11SetTargetSpoolRes\x12\n\n\x02ok\x18\x01 \x02(\x08\x12\x0f\n\x06reason\x18\xff\x01 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'set_target_spool_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETTARGETSPOOLREQ._serialized_start=35
  _SETTARGETSPOOLREQ._serialized_end=69
  _SETTARGETSPOOLRES._serialized_start=71
  _SETTARGETSPOOLRES._serialized_end=119
# @@protoc_insertion_point(module_scope)
